version: '3'
services: 
    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        environment: 
            - MONGODB_INITDB_ROOT_USERNAME=admin
            - MONGODB_INITDB_ROOT_PASSWORD=admin
    mongo-express:
        image: mongo-express
        ports: 
            - 8082:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=mongodb